groups:
  - name: study-members
    reviewers: 2
    usernames:
      - MinhoJJang
      - doxxx93
      - Hamburg-Whale
      - yucori
      - yureutaejin
      - kiku99
      - MarkSon-42
    load_balancing: true
    paths_ignore:
      - ".github/workflows/reviewer-lottery.yaml"
      - ".github/reviewer-lottery.yml"