name: Round Robin PR Reviewer Assignment

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Assign Reviewers
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // 상태 파일 경로
            const STATE_FILE = '.github/reviewer-state.json';
            
            // 리뷰어 목록
            const reviewers = [
              'MinhoJJang',
              'doxxx93',
              'Hamburg-Whale',
              'yucori',
              'yureutaejin',
              'kiku99',
              'MarkSon-42'
            ];

            // 상태 파일 읽기 또는 초기화
            let state;
            try {
              state = JSON.parse(fs.readFileSync(STATE_FILE, 'utf8'));
            } catch (error) {
              state = {
                lastIndex: -1
              };
            }

            // 다음 두 리뷰어 선택
            const getNextReviewers = () => {
              const result = [];
              const total = reviewers.length;
              
              for (let i = 0; i < 2; i++) {
                state.lastIndex = (state.lastIndex + 1) % total;
                result.push(reviewers[state.lastIndex]);
              }
              
              return result;
            };

            // 리뷰어 선택
            const selectedReviewers = getNextReviewers();

            // PR에 리뷰어 할당
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: selectedReviewers
            });

            // 상태 저장
            fs.writeFileSync(STATE_FILE, JSON.stringify(state, null, 2));

            console.log(`Assigned reviewers: ${selectedReviewers.join(', ')}`); 